### ISSUE TITLE
[Bug] 开启“使用Nvidia GPU”后无法正常提取字幕

### ISSUE THREAD

**Issue by moulai** [melon/qingwu-zimu#2]
开启“使用Nvidia GPU”后，提取字幕会出错，提示“字幕提取任务出错，请重试”。关闭这个选项就能正常使用了。

系统：Windows 11
GPU：NVIDIA GeForce RTX 3070
青梧版本：官网下载的整合版，0.9.13
使用模型：从base到large都试过了，都不行。

**Comment by melon** [comment]
> 开启“使用Nvidia GPU”后，提取字幕会出错，提示“字幕提取任务出错，请重试”。关闭这个选项就能正常使用了。
> 
> 系统：Windows 11 GPU：NVIDIA GeForce RTX 3070 青梧版本：官网下载的整合版，0.9.13 使用模型：从base到large都试过了，都不行。

https://zimu.qijingdict.com/zimu/nvidia-gpu-install-tutorial 看一下是不是cuda版本不太对，之前在win 10的cuda 11.8上测试过是正常的
